name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: gleam-lang/setup-erlang@v1.1.3
        with:
          otp-version: 24.0
      - uses: gleam-lang/setup-gleam@v1.0.2
        with:
          gleam-version: 0.18.0
      - run: gleam test
      - run: gleam format --check src test
